name: movetheworld
favicon: null
layout_spectrum: 0.44931912003085017
typography_spectrum: 0.29446503636427224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#70819b'
    - '#5a1b12'
    - '#e6e8e3'
    - '#a1adb9'
    - '#040406'
  brandStrength: 0.3125
  lightness: 0.6981345268432051
  saturation: 0.9909058168996125
  rhythmicContrast: 0.0156284321565181
purpose: []
